services:
  - type: web
    name: telugu-ocr-api
    env: python

    buildCommand: |
      echo "START BUILD"

      apt-get update -y
      apt-get install -y tesseract-ocr tesseract-ocr-tel

      echo "CHECK TESSERACT"
      which tesseract
      tesseract --version

      pip install --upgrade pip
      pip install -r requirements.txt

      echo "BUILD COMPLETE"

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
